name = "FDGrids"
uuid = "28eb41cd-435a-4ede-8bdb-f2685fc03e8c"
version = "0.2.1"
authors = ["Davide Lasagna <davide.lasagna@soton.ac.uk>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
BenchmarkTools = "1.8.0"

[workspace]
projects = ["test", "benchmarks"]
