name = "FDGrids"
uuid = "28eb41cd-435a-4ede-8bdb-f2685fc03e8c"
version = "0.2.1"
authors = ["Davide Lasagna <davide.lasagna@soton.ac.uk>"]

[workspace]
projects = ["test", "benchmarks"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
FDGridsCUDAExt = "CUDA"
